/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsistenciaRouteImport } from './routes/asistencia'
import { Route as CronometroRouteImport } from './routes/cronometro'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as NominaRouteImport } from './routes/nomina'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenciaRoute = AsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const CronometroRoute = CronometroRouteImport.update({
  id: '/cronometro',
  path: '/cronometro',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const NominaRoute = NominaRouteImport.update({
  id: '/nomina',
  path: '/nomina',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/cronometro': typeof CronometroRoute
  '/historial': typeof HistorialRoute
  '/nomina': typeof NominaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/cronometro': typeof CronometroRoute
  '/historial': typeof HistorialRoute
  '/nomina': typeof NominaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/cronometro': typeof CronometroRoute
  '/historial': typeof HistorialRoute
  '/nomina': typeof NominaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asistencia' | '/cronometro' | '/historial' | '/nomina'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asistencia' | '/cronometro' | '/historial' | '/nomina'
  id:
    '__root__' | '/' | '/asistencia' | '/cronometro' | '/historial' | '/nomina'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenciaRoute: typeof AsistenciaRoute
  CronometroRoute: typeof CronometroRoute
  HistorialRoute: typeof HistorialRoute
  NominaRoute: typeof NominaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistencia': {
      id: '/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronometro': {
      id: '/cronometro'
      path: '/cronometro'
      fullPath: '/cronometro'
      preLoaderRoute: typeof CronometroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nomina': {
      id: '/nomina'
      path: '/nomina'
      fullPath: '/nomina'
      preLoaderRoute: typeof NominaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenciaRoute: AsistenciaRoute,
  CronometroRoute: CronometroRoute,
  HistorialRoute: HistorialRoute,
  NominaRoute: NominaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
